Repository GestionCIE/CIE-front, pull requests merged in 2020-06, with the labels that each got.

#25 Developer
  .gitignore
  public/index.html
  src/App.test.js
  src/View/Home/Home.js
  src/View/Public/cie/cie.css
  src/View/Public/cie/cie.js
  src/api/assistance/assistanceApi.js
  src/api/common/eventStatistics.js
  src/api/common/lastActivitySystem.js
  src/api/management/managenmentApi.js
  src/api/profile/profile.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/HeaderManagement.js
  src/components/Header/header.css
  src/components/Header/nofication.js
  src/components/assistance/assistance.css
  src/components/assistance/assistance.js
  src/components/events/eventComponent.js
  src/components/general/general.css
  src/components/general/general.js
  src/components/management/comments.js
  src/components/management/detailActivity.js
  src/components/management/management.css
  src/components/management/management.js
  src/components/menu/PrincipalComponent.js
  src/components/menu/index.css
  src/components/menu/profile.js
  src/components/profile/profile.css
  src/components/profile/profile.js
  src/components/seguimiento/tracingComponent.js
  src/index.css
  src/logo.svg
  src/pages/admin/index.js
  src/pages/landing/about/QuienesSomos.css
  src/pages/landing/about/QuienesSomos.js
  src/pages/landing/cie/cie.css
  src/pages/landing/cie/cie.js
  src/pages/landing/cie/entrepreneur.js
  src/pages/landing/cie/form.js
  src/pages/landing/cie/information.js
  src/pages/landing/login/login.css
  src/pages/landing/login/login.js
  src/pages/landing/login/register.js
  src/pages/landing/menu.js
  src/pages/landing/public.css
  src/pages/landing/public.js
  src/pages/landing/switchContent.js
  src/pages/page.css
  src/pages/page.js
  src/routers/router.js
  src/setupTests.js
Labels: enhancement

#26 se corrigio la interfaz config proyecto
  src/components/FacebookLogin/FacebookLogin.js
  src/components/proyect/ProyectComponent.js
  src/pages/landing/login/login.js
Labels: bug

#27 Developer
  src/api/management/managenmentApi.js
  src/components/management/contentTabs.js
  src/components/management/management.css
  src/components/management/management.js
  src/pages/landing/login/login.js
  src/pages/landing/menu.js
  src/pages/landing/projects/projects.css
  src/pages/landing/projects/projects.js
  src/pages/landing/switchContent.js
Labels: bug, enhancement

#30 Developer
  package.json
  src/api/http.js
  src/assets/calendar.svg
  src/assets/event.svg
  src/components/events/eventComponent.css
  src/components/events/eventComponent.js
  src/components/management/comments.js
  src/components/management/contentTabs.js
  src/components/management/detailActivity.js
  src/components/management/management.css
  src/components/management/management.js
  src/components/menu/index.css
  src/pages/landing/cie/information.js
  src/pages/landing/login/register.js
  src/pages/landing/newEvents.js
  src/pages/landing/public.css
  src/pages/landing/switchContent.js
Labels: enhancement

#31 correccion de la rura getprojects
  src/components/proyect/ProyectComponent.js
  src/routers/router.js
Labels: bug
