Repository GestionCIE/CIE-front, pull requests merged in 2020-07, with the labels that each got.

#36 Developer
  package.json
  src/assets/assistant.svg
  src/assets/escudo americana.jpg
  src/components/assistance/assistance.css
  src/components/assistance/assistance.js
  src/components/assistance/charts.js
  src/components/proyect/ProyectComponent.js
  src/pages/landing/cie/cie.js
Labels: enhancement

#39 grafica
  src/components/management/management.js
  src/components/projectTrace/projectTrace.js
Labels: enhancement

#42 Developer
  package.json
  src/components/Header/nofication.js
  src/components/configuration/configuration.js
  src/components/events/eventComponent.js
  src/components/general/general.js
  src/components/management/management.js
  src/components/projectTrace/granttGraph.js
  src/components/projectTrace/projectTrace.js
  src/components/proyect/ProyectComponent.js
  src/components/proyect/project.js
  src/pages/admin/index.js
  src/pages/page.js
  src/routers/context.js
  src/routers/router.js
  src/socket/socketClient.js
Labels: enhancement, refactoring

#49 fixed async method
  src/pages/landing/cie/form.js
Labels: bug

#52 Developer
  .env.development
  package.json
  src/api/http.js
  src/components/events/eventComponent.css
  src/components/events/eventComponent.js
  src/components/menu/PrincipalComponent.js
  src/components/menu/index.css
  src/pages/admin/index.js
  src/pages/landing/advisers.js
  src/pages/landing/cie/cie.css
  src/pages/landing/cie/form.js
  src/pages/landing/login/login.js
  src/pages/landing/menu.js
  src/pages/landing/public.css
  src/pages/landing/switchContent.js
  src/pages/page.css
  src/pages/page.js
  yarn-error.log
Labels: enhancement, refactoring

#56 Developer
  src/assets/statistics.svg
  src/components/assistance/assistance.js
  src/components/assistance/tracingComponent.js
  src/components/commons/eventStatistics.js
  src/pages/admin/index.js
  src/pages/landing/cie/form.js
  src/pages/landing/menu.js
  src/pages/landing/public.css
  src/pages/landing/switchContent.js
  src/routers/router.js
Labels: bug, enhancement, refactoring
